import {
  gho,
  god,
  gt7,
  horizon,
  last,
  gho1,
  god1,
  gt71,
  horizon1,
  last1,
  asback,
  ret,
  rift,
  sac,
  spiderman,
  spiderman1,
  un,
  ret1,
  rift1,
  sac1,
  un1,
  asm,
  ride4,
} from "../assets/games";
import { cart, home, library, store } from "../assets/icons";
import { newuser, profile1, profile2, profile3 } from "../assets/profilepic";

export const navLinks = [
  { href: "/sarah", label: "Home", img: home },
  { href: "/games", label: "Library", img: library },
  { href: "/products", label: "Gamehub Store", img: store },
];

export const profileusers = [
  {
    img: profile1,
    name: "Sarah",
    last: "Last online 2 hour ago",
    back: "bg-[#6fd8ae]/50",
    hov: "hover:bg-[#6fd8ae]/65",
    id: "/sarah",
    login: "Press to login",
    animation:
      "animate-fade-up animate-once  animate-delay-100 animate-ease-linear",
  },
  {
    img: profile2,
    name: "Kratos",
    last: "Last online 5 hour ago",
    back: "bg-[#cb595b]/50",
    hov: "hover:bg-[#cb595b]/65",
    id: "/kratos",
    login: "Press to login",
    animation:
      "animate-fade-up animate-once animate-delay-300 animate-ease-linear",
  },
  {
    img: profile3,
    name: "Mario",
    last: "Last online 8 hour ago",
    back: "bg-[#254dcf]/50",
    hov: "hover:bg-[#254dcf]/65",
    id: "/mario",
    login: "Press to login",
    animation:
      "animate-fade-up animate-once  animate-delay-500 animate-ease-linear",
  },
  {
    img: newuser,
    name: "Guest/Add User",
    back: "bg-gray-500 backdrop-blur-sm bg-opacity-50 ",
    last: "Create new user",
    hov: "hover:bg-gray-500/65",
    login: "Create new user",
    id: "/register",
    animation:
      "animate-fade-up animate-once animate-delay-700 animate-ease-linear",
  },
];

export const products = [
  {
    id: 1232154,
    imgURL: gho,
    back: gho1,
    label: "Ghost Of Tsushima",
    price: 2500,
    genre: "Action",
    rating: 4.3,
    parent_platforms: 120,
    href: "/games/ghost-of-tsushima-directors-cut",
  },
  {
    id: 1232124,
    imgURL: asm,
    back: asback,
    label: "Assassin's Creed® Mirage",
    price: 2680,
    genre: "RPG",
    rating: 4.6,
    parent_platforms: 120,
    href: "/games/assassins-creed-mirage",
  },
  {
    id: 2432134,
    imgURL: god,
    back: god1,
    label: "God Of War Ragnarok",
    price: 3200,
    genre: "Action",
    rating: 4.5,
    parent_platforms: 120,
    href: "/games/god-of-war-ragnarok",
  },
  {
    id: 34325643,
    imgURL: gt7,
    back: gt71,
    label: "Gran Turismo 7",
    price: 4200,
    genre: "Racing",
    rating: 4.7,
    parent_platforms: 120,
    href: "/games/gran-turismo-7",
  },
  {
    id: 432134,
    imgURL: horizon,
    back: horizon1,
    label: "Horizon Forbidden West",
    price: 3800,
    genre: "Action",
    rating: 4.1,
    parent_platforms: 120,
    href: "/games/horizon-zero-dawn-2",
  },
  {
    id: 554365,
    imgURL: last,
    back: last1,
    label: "Last of us part 1",
    price: 6800,
    genre: "Adventure",
    rating: 4.13,
    parent_platforms: 120,
    href: "/games/the-last-of-us-part-i",
  },
  {
    id: 24326,
    imgURL: ret,
    back: ret1,
    label: "Returnal",
    price: 2300,
    genre: "Multiplayer",
    rating: 4.6,
    parent_platforms: 120,
    href: "/games/returnal",
  },
  {
    id: 754363,
    imgURL: rift,
    back: rift1,
    label: "Ratchet and clank",
    price: 3100,
    genre: "Multiplayer",
    rating: 4.5,
    parent_platforms: 120,
    href: "/games/ratchet-clank",
  },
  {
    id: 824324,
    imgURL: sac,
    back: sac1,
    label: "Sackboy",
    price: 1500,
    genre: "Adventure",
    rating: 4.5,
    parent_platforms: 120,
    href: "/games/sackboy-a-big-adventure-2",
  },
  {
    id: 9163412,
    imgURL: spiderman,
    back: spiderman1,
    label: "Spiderman",
    price: 2400,
    genre: "Role-Playing",
    rating: 5,
    parent_platforms: 120,
    href: "/games/marvels-spider-man",
  },
  {
    id: 10543,
    imgURL: un,
    back: un1,
    label: "Uncharted",
    price: 1400,
    genre: "Action",
    rating: 4.5,
    parent_platforms: 120,
    href: "/games/uncharted-legacy-of-thieves-collection",
  },

  {
    id: 10541,
    imgURL: ride4,
    back: un1,
    label: "Ride 4",
    price: 2500,
    genre: "Racing",
    rating: 4.5,
    parent_platforms: 120,
    href: "/games/ride-4",
  },
];
